'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';

// Map questions to concepts they test
const QUESTION_TO_CONCEPT_MAP: Record<string, number> = {
  'q1': 1,  // Sound generation
  'q2': 3,  // Frequency
  'q3': 4,  // Intensity
  'q4': 1,  // Medium/propagation
  'q5': 1,  // Sound generation
  'q6': 4,  // Sound level
  'q7': 1,  // Sound travel
  'q8': 1,  // Sound generation
  'q9': 5,  // Types of sound
  'q10': 5  // Ultrasonic uses
};

const ALL_CONCEPTS = [
  {
    id: 1,
    title: 'Sound Generation and Vibration',
    emoji: '🔊',
    color: 'from-blue-400 to-cyan-500',
    summary: 'Sound is generated by rhythmic vibration. It travels through a medium (air, water, solids). No sound in vacuum.',
    keyPoints: [
      'Sound = Vibration of objects',
      'Needs a medium to travel',
      'Different materials transmit sound at different speeds'
    ]
  },
  {
    id: 2,
    title: 'Oscillation and Oscillatory Motion',
    emoji: '⚡',
    color: 'from-purple-400 to-pink-500',
    summary: 'Oscillator moves back and forth. One complete back-and-forth movement = one oscillation. Motion on either side of center = oscillatory motion.',
    keyPoints: [
      'Oscillator: Back and forth motion',
      'One oscillation = Complete cycle',
      'Elasticity causes vibrations'
    ]
  },
  {
    id: 3,
    title: 'Time Period and Frequency',
    emoji: '⏰',
    color: 'from-green-400 to-emerald-500',
    summary: 'Time period (T) = time for one oscillation. Frequency (n) = 1/T = oscillations per second. Unit: Hertz (Hz).',
    keyPoints: [
      'Frequency = 1 / Time Period',
      'Unit: Hertz (Hz)',
      '1 Hz = 1 oscillation/second',
      '100 Hz = 100 oscillations/second'
    ]
  },
  {
    id: 4,
    title: 'Pitch and Intensity',
    emoji: '🎶',
    color: 'from-orange-400 to-red-500',
    summary: 'Pitch depends on frequency. Higher frequency = higher pitch. Intensity relates to loudness. Measured in decibels (dB).',
    keyPoints: [
      'Pitch ∝ Frequency',
      'Sound level measured in dB',
      'Tuning = adjusting pitch',
      '0 dB = threshold of hearing',
      '130 dB = threshold of pain'
    ]
  },
  {
    id: 5,
    title: 'Types of Sound',
    emoji: '🌊',
    color: 'from-indigo-400 to-purple-500',
    summary: 'Audible: 20-20,000 Hz. Infrasonic: < 20 Hz (whales, elephants). Ultrasonic: > 20,000 Hz (bats, SONAR).',
    keyPoints: [
      'Audible: 20 Hz to 20,000 Hz',
      'Infrasonic: Below 20 Hz',
      'Ultrasonic: Above 20,000 Hz',
      'SONAR uses ultrasonic sound'
    ]
  }
];

export default function Revision() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const [conceptsToReview, setConceptsToReview] = useState<number[]>([]);
  const [currentConcept, setCurrentConcept] = useState(0);
  const [isPerfectScore, setIsPerfectScore] = useState(false);

  useEffect(() => {
    const userId = sessionStorage.getItem('userId');
    if (!userId) {
      router.push('/login');
      return;
    }

    // Get wrong questions from URL
    const wrongParam = searchParams.get('wrong');
    const score = parseInt(searchParams.get('score') || '0');

    if (score === 100) {
      // Perfect score - show all concepts as summary
      setIsPerfectScore(true);
      setConceptsToReview([1, 2, 3, 4, 5]);
    } else if (wrongParam) {
      // Get concepts related to wrong questions
      const wrongQuestions = JSON.parse(decodeURIComponent(wrongParam));
      const concepts = new Set<number>();
      
      wrongQuestions.forEach((qId: string) => {
        const conceptId = QUESTION_TO_CONCEPT_MAP[qId];
        if (conceptId) concepts.add(conceptId);
      });
      
      setConceptsToReview(Array.from(concepts).sort());
    } else {
      // Default: show all
      setConceptsToReview([1, 2, 3, 4, 5]);
    }
  }, [router, searchParams]);

  const handleNext = () => {
    if (currentConcept < conceptsToReview.length - 1) {
      setCurrentConcept(prev => prev + 1);
    }
  };

  const handlePrevious = () => {
    if (currentConcept > 0) {
      setCurrentConcept(prev => prev - 1);
    }
  };

  const handleComplete = async () => {
    if (isPerfectScore) {
      // Perfect score - mark chapter complete
      try {
        const userId = sessionStorage.getItem('userId');
        
        await fetch(`/api/chapter/${params.id}/progress`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            userId: parseInt(userId || '0'),
            stageCompleted: 5,
            score: 100
          })
        });

        router.push('/dashboard');
      } catch (error) {
        console.error('Error:', error);
        alert('Failed to save progress.');
      }
    } else {
      // Retake test
      router.push(`/chapter/${params.id}/test?retake=true`);
    }
  };

  if (conceptsToReview.length === 0) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-800">Loading revision...</p>
        </div>
      </div>
    );
  }

  const conceptId = conceptsToReview[currentConcept];
  const concept = ALL_CONCEPTS.find(c => c.id === conceptId);
  const progress = ((currentConcept + 1) / conceptsToReview.length) * 100;

  if (!concept) return null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-4">
      <div className="max-w-3xl mx-auto py-8">
        {/* Header */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-6">
          <div className="flex items-center justify-between mb-4">
            <h1 className="text-2xl font-bold text-gray-900">
              {isPerfectScore ? '🌟 Chapter Summary' : '📝 Revision - Learn from Mistakes'}
            </h1>
            <span className="px-3 py-1 bg-purple-100 text-purple-800 text-sm rounded-full font-semibold">
              Stage 5 of 5
            </span>
          </div>

          <p className="text-gray-800 mb-4">
            {isPerfectScore 
              ? 'Congratulations on your perfect score! Here\'s a quick summary of everything you\'ve learned.'
              : `Let's review the concepts you need to strengthen. Focus on these ${conceptsToReview.length} topics.`
            }
          </p>

          {/* Progress */}
          <div className="mb-4">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium text-gray-900">
                Concept {currentConcept + 1} of {conceptsToReview.length}
              </span>
              <span className="text-sm font-semibold text-purple-600">
                {Math.round(progress)}%
              </span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-2">
              <div
                className="bg-purple-600 h-2 rounded-full transition-all duration-500"
                style={{ width: `${progress}%` }}
              ></div>
            </div>
          </div>
        </div>

        {/* Concept Review */}
        <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
          {/* Header */}
          <div className={`bg-gradient-to-r ${concept.color} p-6`}>
            <div className="flex items-center">
              <span className="text-6xl mr-4">{concept.emoji}</span>
              <h2 className="text-3xl font-bold text-white">
                {concept.title}
              </h2>
            </div>
          </div>

          <div className="p-8">
            {/* Summary */}
            <div className="bg-purple-50 rounded-lg p-6 mb-6 border-2 border-purple-300">
              <h3 className="text-lg font-bold text-purple-900 mb-3">
                📖 Key Concept:
              </h3>
              <p className="text-gray-900 text-lg leading-relaxed">
                {concept.summary}
              </p>
            </div>

            {/* Key Points */}
            <div className="bg-yellow-50 rounded-lg p-6 border-2 border-yellow-300">
              <h3 className="text-lg font-bold text-gray-900 mb-4">
                ✨ Remember These Points:
              </h3>
              <ul className="space-y-2">
                {concept.keyPoints.map((point, idx) => (
                  <li key={idx} className="flex items-start">
                    <span className="text-green-600 mr-2 text-xl">✓</span>
                    <span className="text-gray-900">{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Navigation */}
          <div className="p-6">
            <div className="flex justify-between items-center pt-6 border-t border-gray-200">
              <button
                onClick={handlePrevious}
                disabled={currentConcept === 0}
                className="px-6 py-3 rounded-lg border-2 border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition font-semibold"
              >
                ← Previous
              </button>

              {currentConcept === conceptsToReview.length - 1 ? (
                <button
                  onClick={handleComplete}
                  className={`px-6 py-3 rounded-lg text-white font-semibold transition ${
                    isPerfectScore 
                      ? 'bg-green-600 hover:bg-green-700' 
                      : 'bg-purple-600 hover:bg-purple-700'
                  }`}
                >
                  {isPerfectScore ? '✅ Complete Chapter!' : '🔄 Retake Test'}
                </button>
              ) : (
                <button
                  onClick={handleNext}
                  className="px-6 py-3 rounded-lg bg-purple-600 text-white hover:bg-purple-700 transition font-semibold"
                >
                  Next Concept →
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Progress Dots */}
        <div className="mt-6 text-center">
          <div className="flex items-center justify-center space-x-2">
            {conceptsToReview.map((_, index) => (
              <div
                key={index}
                className={`h-2 w-12 rounded-full transition-all ${
                  index === currentConcept
                    ? 'bg-purple-600'
                    : index < currentConcept
                    ? 'bg-green-500'
                    : 'bg-gray-300'
                }`}
              ></div>
            ))}
          </div>
          <p className="text-sm text-gray-800 mt-2">
            {isPerfectScore 
              ? 'Perfect score! Review complete curriculum.'
              : 'Review these concepts, then retake the test.'}
          </p>
        </div>
      </div>
    </div>
  );
}
