
import { CourseModule } from './types';

export const science7: CourseModule[] = [
  {
    chapterNumber: 1,
    chapterName: "The Living World: Adaptations and Classification",
    file: "chapter-1-science-7-living-world.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 2,
    chapterName: "Plants: Structure and Function",
    file: "chapter-2-science-7-plants.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 3,
    chapterName: "Properties of Natural Resources",
    file: "chapter-3-science-7-natural-resources.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 4,
    chapterName: "Nutrition in Living Organisms",
    file: "chapter-4-science-7-nutrition.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 5,
    chapterName: "Food Safety",
    file: "chapter-5-science-7-food-safety.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 6,
    chapterName: "Measurement of Physical Quantities",
    file: "chapter-6-science-7-measurement.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 7,
    chapterName: "Motion, Force and Work",
    file: "chapter-7-science-7-motion-force-work.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 8,
    chapterName: "Static Electricity",
    file: "chapter-8-science-7-static-electricity.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 9,
    chapterName: "Heat",
    file: "chapter-9-science-7-heat.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 10,
    chapterName: "Disasters: Famine, water scarcity, Volcano, Tsunami",
    file: "chapter-10-disasters.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 11,
    chapterName: "Cell Structure and Micro-organisms",
    file: "chapter-11-cell-structure-micro-organisms.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 12,
    chapterName: "The Muscular System and Digestive System in Human Beings",
    file: "chapter-12-muscular-digestive-system.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 13,
    chapterName: "Changes – Physical and Chemical",
    file: "chapter-13-physical-chemical-changes.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
  {
    chapterNumber: 16,
    chapterName: "Natural Resources",
    file: "chapter-16-natural-resources.json",
    grade: 7,
    subject: "Science",
    status: "completed",
  },
];
